POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyNGNkZGQzOGNjMjQ3M2JkNzBjNGJkMiIsImlhdCI6MTY0OTI1MDU1MSwiZXhwIjoxNjQ5MjU0MTUxfQ.MZzO7JEEZ-qqoKUMNPNHbYT9C-F7n9wTWdTexX4HeOM

{
  "title": "Hello",
  "author": "me",
  "url": "localhost",
  "likes": 5
}